nordvpn:
  countries:
    random: true
    Vietnam: true
    Luxembourg: true
    Germany: true
    France: true
    UK: true
    US: true
    Netherlands: true
    Sweden: true
    Switzerland: true
    Spain: true
  user: V646NxZDB64kfiuy4gtji4Qi
  pass: thA3GtcRUEwDwnugDFcGseoB
  network: 31.94.70.126/32

proxies:
  count: 20
  base_port: 8880
  username: badvibez
  password: forever

ufw:
  enable: true
