nordvpn:
  user: "your_nordvpn_user"
  pass: "your_nordvpn_pass"
  network: "31.94.70.126/32" # whitelist IP

proxies:
  count: 20
  base_port: 8881
  username: "proxyuser"  # Proxy username
  password: "proxypass"  # Proxy password

ufw:
  enable: true  # Set to false if you don't want UFW rules
