nordvpn:
  user: "your_nordvpn_user"
  pass: "your_nordvpn_pass"
  country: "US"  # Specify country or set to "random"
  auto_connect: true
  network: "31.94.70.126/32"

proxies:
  count: 5
  base_port: 8888
  username: "proxyuser"
  password: "proxypass"

ufw:
  enable: true